#!/usr/bin/env ruby
require 'date'

def exit_with_usage_instructions
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers [Name] [MM/DD Birthday]`
EOS
  exit
end

exit_with_usage_instructions if ARGV.empty? || ARGV.size > 2

original_name = ARGV[0]
cheerable_name = original_name.upcase.gsub(/[^A-Z]/, "")

exit_with_usage_instructions if cheerable_name.empty?

cheerable_name.each_char do |char|
  article = "n" if "HALFNORSEMIX".include? char
  puts "Give me a#{article}... #{char}"
end
puts "#{original_name}’s just GRAND!"
puts ""

def print_birthday_error
  puts "I would wish you a Happy Birthday, if I knew when that was!"
end

def get_bday_count(date)
  birthday = Date.parse(date)
  today = Date.today
  count = (birthday - today) % 365
  count.to_i
end

birthday = ARGV[1]

if birthday.nil? || birthday.length > 5
  print_birthday_error
else
  begin
    count = get_bday_count(birthday)
    puts "Awesome! Your birthday is in #{count} days! Happy Birthday in advance!"
  rescue
    print_birthday_error
  end
end

